# Generated by Django 6.0.3 on 2026-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CountryCode',
        ),
    ]
