# Generated by Django 6.0.3 on 2026-04-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='school',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
