# Generated by Django 6.0.3 on 2026-04-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_course_created_by_course_verified_school_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
