# Generated by Django 6.0.3 on 2026-04-06 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_course_verified_alter_school_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='roletag',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
