# Generated by Django 6.0.3 on 2026-04-08 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_roletag_created_by_roletag_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='graduated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='starting_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('phd', 'PHD'), ('masters', 'MASTERS'), ('bachelor', 'BACHELOR'), ('diploma', 'DIPLOMA'), ('others', 'OTHERS')], max_length=10),
        ),
    ]
