# Generated by Django 6.0.3 on 2026-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_education_ending_date_education_graduated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
