# Generated by Django 6.0.3 on 2026-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_education_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='acc_created_date',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.IntegerField(),
        ),
    ]
