# Generated by Django 6.0.3 on 2026-04-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_profile_achievement_user_alter_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='infineon',
        ),
    ]
